spring:
  application:
    name: recipe_manager

  datasource:
    url: jdbc:postgresql://localhost:5432/trabalhoBD
    username: postgres
    password: 2723
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
